// examples/vue-demo/src/App.vue
<script setup lang="ts">
import UserProfile from './components/UserProfile.vue';
import Counter from './components/Counter.vue';
import ThemeToggle from './components/ThemeToggle.vue';
</script>

<template>
  <div class="root">
    <header class="header">
      <h1 class="title">SafeStorage — Vue Demo</h1>
      <p class="subtitle">
        All values below are encrypted in localStorage. Open DevTools → Application → Local Storage to see the ciphertext.
      </p>
    </header>

    <main class="main">
      <section class="section">
        <h2 class="section-title">useStorage — User Profile</h2>
        <p class="hint">Persists a structured object. Refresh the page — values survive.</p>
        <UserProfile />
      </section>

      <section class="section">
        <h2 class="section-title">useStorage — Counter</h2>
        <p class="hint">Reactive ref backed by encrypted storage. Refresh to confirm.</p>
        <Counter />
      </section>

      <section class="section">
        <h2 class="section-title">useStorage — Theme Preference</h2>
        <p class="hint">Simple string preference persisted with encryption.</p>
        <ThemeToggle />
      </section>
    </main>
  </div>
</template>

<style scoped>
.root { min-height: 100vh; background: #0f172a; color: #e2e8f0; padding: 2rem; }
.header { max-width: 760px; margin: 0 auto 2.5rem; text-align: center; }
.title { font-size: 2rem; font-weight: 700; color: #a78bfa; margin-bottom: 0.75rem; }
.subtitle { color: #94a3b8; line-height: 1.6; }
.main { max-width: 760px; margin: 0 auto; display: flex; flex-direction: column; gap: 1.5rem; }
.section { background: #1e293b; border-radius: 12px; padding: 1.5rem; border: 1px solid #334155; }
.section-title { font-size: 1.1rem; font-weight: 600; color: #c4b5fd; margin-bottom: 0.4rem; }
.hint { color: #64748b; font-size: 0.875rem; margin-bottom: 1rem; }
</style>

// examples/angular-demo/src/app/app.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { SafeStorageService } from '@safestorage/angular';

interface Profile {
  name: string;
  email: string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent implements OnInit {
  private readonly storage = inject(SafeStorageService);

  // Signal-based API (Angular 16+) — initialized after inject()
  readonly theme = this.storage.toSignal<string>('theme', 'system');
  readonly themes = ['light', 'dark', 'system'];

  // Manual state for profile demo
  profile: Profile | null = null;
  nameInput = '';
  emailInput = '';

  // Counter backed by encrypted storage
  count = 0;

  async ngOnInit() {
    this.profile = (await this.storage.get<Profile>('profile')) ?? null;
    this.count = (await this.storage.get<number>('counter')) ?? 0;
  }

  async saveProfile() {
    if (!this.nameInput.trim() || !this.emailInput.trim()) return;
    const p: Profile = { name: this.nameInput, email: this.emailInput };
    await this.storage.set('profile', p);
    this.profile = p;
    this.nameInput = '';
    this.emailInput = '';
  }

  async clearProfile() {
    await this.storage.remove('profile');
    this.profile = null;
  }

  async increment() {
    this.count++;
    await this.storage.set('counter', this.count);
  }

  async decrement() {
    this.count--;
    await this.storage.set('counter', this.count);
  }

  async reset() {
    this.count = 0;
    await this.storage.set('counter', 0);
  }

  async setTheme(t: string) {
    await this.storage.setSignal('theme', t);
  }
}

<div class="root">
  <header class="header">
    <h1 class="title">SafeStorage — Angular Demo</h1>
    <p class="subtitle">
      All values below are encrypted in localStorage. Open DevTools → Application → Local Storage to see the ciphertext.
    </p>
  </header>

  <main class="main">

    <!-- Profile: Promise-based API -->
    <section class="section">
      <h2 class="section-title">SafeStorageService — User Profile</h2>
      <p class="hint">Persists a structured object using the Promise API. Refresh the page — values survive.</p>

      <ng-container *ngIf="profile; else profileForm">
        <div class="card">
          <div class="row"><span class="label">Name</span> {{ profile.name }}</div>
          <div class="row"><span class="label">Email</span> {{ profile.email }}</div>
          <button class="btn danger" (click)="clearProfile()">Clear Profile</button>
        </div>
      </ng-container>
      <ng-template #profileForm>
        <div class="form">
          <input class="input" placeholder="Name" [(ngModel)]="nameInput" />
          <input class="input" placeholder="Email" [(ngModel)]="emailInput" />
          <button class="btn" (click)="saveProfile()">Save Profile</button>
        </div>
      </ng-template>
    </section>

    <!-- Counter: Promise-based API -->
    <section class="section">
      <h2 class="section-title">SafeStorageService — Counter</h2>
      <p class="hint">Simple numeric value persisted with encryption. Refresh to confirm.</p>
      <div class="counter-row">
        <button class="btn icon" (click)="decrement()">−</button>
        <span class="count">{{ count }}</span>
        <button class="btn icon" (click)="increment()">+</button>
        <button class="btn-ghost" (click)="reset()">Reset</button>
      </div>
    </section>

    <!-- Theme: Signal-based API -->
    <section class="section">
      <h2 class="section-title">toSignal — Theme Preference</h2>
      <p class="hint">Angular signal backed by encrypted storage. Reactive — no manual subscription.</p>
      <div class="pill-row">
        <button
          *ngFor="let t of themes"
          [class]="'pill ' + (theme() === t ? 'active' : '')"
          (click)="setTheme(t)"
        >{{ t }}</button>
      </div>
    </section>

  </main>
</div>
