// examples/react-demo/src/Counter.tsx
import React from 'react';
import { useEncryptedState } from '@safestorage/react';

export const Counter = () => {
  const [count, setCount] = useEncryptedState('counter', 0);

  return (
    <div style={styles.row}>
      <button style={styles.btn} onClick={() => setCount(c => c - 1)}>−</button>
      <span style={styles.count}>{count}</span>
      <button style={styles.btn} onClick={() => setCount(c => c + 1)}>+</button>
      <button style={styles.reset} onClick={() => setCount(0)}>Reset</button>
    </div>
  );
};

const styles: Record<string, React.CSSProperties> = {
  row: { display: 'flex', alignItems: 'center', gap: '1rem' },
  btn: {
    background: '#0284c7', color: '#fff', border: 'none', borderRadius: 8,
    width: 40, height: 40, fontSize: '1.25rem', cursor: 'pointer', fontWeight: 700,
  },
  count: { fontSize: '2rem', fontWeight: 700, minWidth: 60, textAlign: 'center' },
  reset: {
    background: 'transparent', color: '#64748b', border: '1px solid #334155',
    borderRadius: 8, padding: '0.4rem 0.75rem', cursor: 'pointer',
  },
};

// examples/vue-demo/src/components/Counter.vue
<script setup lang="ts">
import { useStorage } from '@safestorage/vue';

const { value: count, set: setCount } = useStorage('counter', 0, {
  password: 'vue-demo-secret-key',
  namespace: 'vue-demo::',
});

function increment() { setCount(count.value + 1); }
function decrement() { setCount(count.value - 1); }
function reset() { setCount(0); }
</script>

<template>
  <div class="row">
    <button class="btn" @click="decrement">−</button>
    <span class="count">{{ count }}</span>
    <button class="btn" @click="increment">+</button>
    <button class="reset" @click="reset">Reset</button>
  </div>
</template>

<style scoped>
.row { display: flex; align-items: center; gap: 1rem; }
.btn {
  background: #7c3aed; color: #fff; border: none; border-radius: 8px;
  width: 40px; height: 40px; font-size: 1.25rem; cursor: pointer; font-weight: 700;
}
.count { font-size: 2rem; font-weight: 700; min-width: 60px; text-align: center; }
.reset {
  background: transparent; color: #64748b; border: 1px solid #334155;
  border-radius: 8px; padding: 0.4rem 0.75rem; cursor: pointer;
}
</style>
